# Generated by Django 4.2.13 on 2024-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saveservice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymodel", name="phone", field=models.CharField(max_length=20),
        ),
    ]
